apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-apps
spec:
  generators:
    - git:
        directories:
          - path: apps/*
        repoURL: https://github.com/ITlusions/ITL.Demo.Gallery.git
        revision: main
  template:
    metadata:
      name: {{ values.submodules.namespace }}
    spec:
      destination:
        namespace: {{ values.submodules.namespace }}
        server: https://kubernetes.default.svc
      project: default
      source:
        repoURL: {{ values.submodules.repoURL }}
        targetRevision: main
        path: .
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
